traits = {
    "has_emblem": ["8-bit", "Country", "Disco", "Emo", "Jazz", "Heartsteel", "Hyperpop", "K/DA", "Pentakill", "Punk", 
                "True Damage", "Big Shot", "Bruiser", "Crowd Diver", "Dazzler", "Edgelord", "Executioner", "Mosher", 
                "Guardian", "Rapidfire", "Sentinel", "Superfan", "Spellweaver"],
    "no_emblem": ["Breakout", "EDM", "ILLBEATS", "Maestro", "Mixmaster", "Wildcard"]
}

champions_by_cost = {
    1: [
        {"name": "Annie", "traits": ["Emo", "Spellweaver"], "cost": 1},
        {"name": "Corki", "traits": ["8-bit", "Big Shot"], "cost": 1},
        {"name": "Evelynn", "traits": ["K/DA", "Crowd Diver"], "cost": 1},
        {"name": "Jinx", "traits": ["Punk", "Rapidfire"], "cost": 1},
        {"name": "Kennen", "traits": ["True Damage", "Superfan", "Guardian"], "cost": 1},
        {"name": "K'Sante", "traits": ["Heartsteel", "Sentinel"], "cost": 1},
        {"name": "Lillia", "traits": ["K/DA", "Superfan", "Sentinel"], "cost": 1},
        {"name": "Nami", "traits": ["Disco", "Dazzler"], "cost": 1},
        {"name": "Olaf", "traits": ["Pentakill", "Bruiser"], "cost": 1},
        {"name": "Taric", "traits": ["Disco", "Guardian"], "cost": 1},
        {"name": "Tahm Kench", "traits": ["Country", "Bruiser"], "cost": 1},
        {"name": "Vi", "traits": ["Punk", "Mosher"], "cost": 1},
        {"name": "Yasuo", "traits": ["True Damage", "Edgelord"], "cost": 1},
    ],
    2: [
        {"name": "Aphelios", "traits": ["Heartsteel", "Rapidfire"], "cost": 2},
        {"name": "Bard", "traits": ["Jazz", "Dazzler"], "cost": 2},
        {"name": "Garen", "traits": ["8-bit", "Sentinel"], "cost": 2},
        {"name": "Gnar", "traits": ["Pentakill", "Superfan", "Mosher"], "cost": 2},
        {"name": "Gragas", "traits": ["Disco", "Spellweaver", "Bruiser"], "cost": 2},
        {"name": "Jax", "traits": ["EDM", "Mosher"], "cost": 2},
        {"name": "Kai'Sa", "traits": ["K/DA", "Big Shot"], "cost": 2},
        {"name": "Katarina", "traits": ["Country", "Crowd Diver"], "cost": 2},
        {"name": "Kayle", "traits": ["Pentakill", "Edgelord"], "cost": 2},
        {"name": "Pantheon", "traits": ["Punk", "Guardian"], "cost": 2},
        {"name": "Senna", "traits": ["True Damage", "Rapidfire"], "cost": 2},
        {"name": "Seraphine", "traits": ["K/DA", "Spellweaver"], "cost": 2},
        {"name": "Twitch", "traits": ["Punk", "Executioner"], "cost": 2},
    ],
    3: [
        {"name": "Amumu", "traits": ["Emo", "Guardian"], "cost": 3},
        {"name": "Ekko", "traits": ["True Damage", "Spellweaver", "Sentinel"], "cost": 3},
        {"name": "Lulu", "traits": ["Hyperpop", "Spellweaver"], "cost": 3},
        {"name": "Lux", "traits": ["EDM", "Dazzler"], "cost": 3},
        {"name": "Miss Fortune", "traits": ["Jazz", "Big Shot"], "cost": 3},
        {"name": "Mordekaiser", "traits": ["Pentakill", "Sentinel"], "cost": 3},
        {"name": "Neeko", "traits": ["K/DA", "Superfan", "Guardian"], "cost": 3},
        {"name": "Riven", "traits": ["8-bit", "Edgelord"], "cost": 3},
        {"name": "Samira", "traits": ["Country", "Executioner"], "cost": 3},
        {"name": "Sett", "traits": ["Heartsteel", "Bruiser", "Mosher"], "cost": 3},
        {"name": "Urgot", "traits": ["Country", "Mosher"], "cost": 3},
        {"name": "Vex", "traits": ["Emo", "Executioner"], "cost": 3},
        {"name": "Yone", "traits": ["Heartsteel", "Edgelord", "Crowd Diver"], "cost": 3},
    ],
    4: [
        {"name": "Ahri", "traits": ["K/DA", "Spellweaver"], "cost": 4},
        {"name": "AkaliK", "traits": ["K/DA", "Executioner", "Breakout"], "cost": 4},
        {"name": "AkaliT", "traits": ["True Damage", "Executioner", "Breakout"], "cost": 4},
        {"name": "Blitzcrank", "traits": ["Disco", "Sentinel"], "cost": 4},
        {"name": "Caitlyn", "traits": ["8-bit", "Rapidfire"], "cost": 4},
        {"name": "Ezreal", "traits": ["Heartsteel", "Big Shot"], "cost": 4},
        {"name": "Karthus", "traits": ["Pentakill", "Executioner"], "cost": 4},
        {"name": "Poppy", "traits": ["Emo", "Mosher"], "cost": 4},
        {"name": "Thresh", "traits": ["Country", "Guardian"], "cost": 4},
        {"name": "Twisted Fate", "traits": ["Disco", "Dazzler"], "cost": 4},
        {"name": "Viego", "traits": ["Pentakill", "Edgelord"], "cost": 4},
        {"name": "Zac", "traits": ["EDM", "Bruiser"], "cost": 4},
        {"name": "Zed", "traits": ["EDM", "Crowd Diver"], "cost": 4},
    ],
    5: [
        {"name": "Illaoi", "traits": ["ILLBEATS", "Bruiser"], "cost": 5},
        {"name": "Jhin", "traits": ["Maestro", "Big Shot"], "cost": 5},
        {"name": "Kayn", "traits": ["Heartsteel", "Edgelord", "Wildcard"], "cost": 5},
        {"name": "Lucian", "traits": ["Jazz", "Rapidfire"], "cost": 5},
        {"name": "Qiyana", "traits": ["True Damage", "Crowd Diver"], "cost": 5},
        {"name": "Sona", "traits": ["Mixmaster", "Spellweaver"], "cost": 5},
        {"name": "Yorick", "traits": ["Pentakill", "Mosher", "Guardian"], "cost": 5},
        {"name": "Ziggs", "traits": ["Hyperpop", "Dazzler"], "cost": 5},
    ]
}

champions_by_name = {
    "Annie": {"name": "Annie", "traits": ["Emo", "Spellweaver"], "cost": 1},
    "Corki": {"name": "Corki", "traits": ["8-bit", "Big Shot"], "cost": 1},
    "Evelynn": {"name": "Evelynn", "traits": ["K/DA", "Crowd Diver"], "cost": 1},
    "Jinx": {"name": "Jinx", "traits": ["Punk", "Rapidfire"], "cost": 1},
    "Kennen": {"name": "Kennen", "traits": ["True Damage", "Superfan", "Guardian"], "cost": 1},
    "K'Sante": {"name": "K'Sante", "traits": ["Heartsteel", "Sentinel"], "cost": 1},
    "Lillia": {"name": "Lillia", "traits": ["K/DA", "Superfan", "Sentinel"], "cost": 1},
    "Nami": {"name": "Nami", "traits": ["Disco", "Dazzler"], "cost": 1},
    "Olaf": {"name": "Olaf", "traits": ["Pentakill", "Bruiser"], "cost": 1},
    "Taric": {"name": "Taric", "traits": ["Disco", "Guardian"], "cost": 1},
    "Tahm Kench": {"name": "Tahm Kench", "traits": ["Country", "Bruiser"], "cost": 1},
    "Vi": {"name": "Vi", "traits": ["Punk", "Mosher"], "cost": 1},
    "Yasuo": {"name": "Yasuo", "traits": ["True Damage", "Edgelord"], "cost": 1},
    "Aphelios": {"name": "Aphelios", "traits": ["Heartsteel", "Rapidfire"], "cost": 2},
    "Bard": {"name": "Bard", "traits": ["Jazz", "Dazzler"], "cost": 2},
    "Garen": {"name": "Garen", "traits": ["8-bit", "Sentinel"], "cost": 2},
    "Gnar": {"name": "Gnar", "traits": ["Pentakill", "Superfan", "Mosher"], "cost": 2},
    "Gragas": {"name": "Gragas", "traits": ["Disco", "Spellweaver", "Bruiser"], "cost": 2},
    "Jax": {"name": "Jax", "traits": ["EDM", "Mosher"], "cost": 2},
    "Kai'Sa": {"name": "Kai'Sa", "traits": ["K/DA", "Big Shot"], "cost": 2},
    "Katarina": {"name": "Katarina", "traits": ["Country", "Crowd Diver"], "cost": 2},
    "Kayle": {"name": "Kayle", "traits": ["Pentakill", "Edgelord"], "cost": 2},
    "Pantheon": {"name": "Pantheon", "traits": ["Punk", "Guardian"], "cost": 2},
    "Senna": {"name": "Senna", "traits": ["True Damage", "Rapidfire"], "cost": 2},
    "Seraphine": {"name": "Seraphine", "traits": ["K/DA", "Spellweaver"], "cost": 2},
    "Twitch": {"name": "Twitch", "traits": ["Punk", "Executioner"], "cost": 2},
    "Amumu": {"name": "Amumu", "traits": ["Emo", "Guardian"], "cost": 3},
    "Ekko": {"name": "Ekko", "traits": ["True Damage", "Spellweaver", "Sentinel"], "cost": 3},
    "Lulu": {"name": "Lulu", "traits": ["Hyperpop", "Spellweaver"], "cost": 3},
    "Lux": {"name": "Lux", "traits": ["EDM", "Dazzler"], "cost": 3},
    "Miss Fortune": {"name": "Miss Fortune", "traits": ["Jazz", "Big Shot"], "cost": 3},
    "Mordekaiser": {"name": "Mordekaiser", "traits": ["Pentakill", "Sentinel"], "cost": 3},
    "Neeko": {"name": "Neeko", "traits": ["K/DA", "Superfan", "Guardian"], "cost": 3},
    "Riven": {"name": "Riven", "traits": ["8-bit", "Edgelord"], "cost": 3},
    "Samira": {"name": "Samira", "traits": ["Country", "Executioner"], "cost": 3},
    "Sett": {"name": "Sett", "traits": ["Heartsteel", "Bruiser", "Mosher"], "cost": 3},
    "Urgot": {"name": "Urgot", "traits": ["Country", "Mosher"], "cost": 3},
    "Vex": {"name": "Vex", "traits": ["Emo", "Executioner"], "cost": 3},
    "Yone": {"name": "Yone", "traits": ["Heartsteel", "Edgelord", "Crowd Diver"], "cost": 3},
    "Ahri": {"name": "Ahri", "traits": ["K/DA", "Spellweaver"], "cost": 4},
    "AkaliK": {"name": "Akali", "traits": ["K/DA", "Executioner", "Breakout"], "cost": 4},
    "AkaliT": {"name": "Akali", "traits": ["True Damage", "Executioner", "Breakout"], "cost": 4},
    "Blitzcrank": {"name": "Blitzcrank", "traits": ["Disco", "Sentinel"], "cost": 4},
    "Caitlyn": {"name": "Caitlyn", "traits": ["8-bit", "Rapidfire"], "cost": 4},
    "Ezreal": {"name": "Ezreal", "traits": ["Heartsteel", "Big Shot"], "cost": 4},
    "Karthus": {"name": "Karthus", "traits": ["Pentakill", "Executioner"], "cost": 4},
    "Poppy": {"name": "Poppy", "traits": ["Emo", "Mosher"], "cost": 4},
    "Thresh": {"name": "Thresh", "traits": ["Country", "Guardian"], "cost": 4},
    "Twisted Fate": {"name": "Twisted Fate", "traits": ["Disco", "Dazzler"], "cost": 4},
    "Viego": {"name": "Viego", "traits": ["Pentakill", "Edgelord"], "cost": 4},
    "Zac": {"name": "Zac", "traits": ["EDM", "Bruiser"], "cost": 4},
    "Zed": {"name": "Zed", "traits": ["EDM", "Crowd Diver"], "cost": 4},
    "Illaoi": {"name": "Illaoi", "traits": ["ILLBEATS", "Bruiser"], "cost": 5},
    "Jhin": {"name": "Jhin", "traits": ["Maestro", "Big Shot"], "cost": 5},
    "Kayn": {"name": "Kayn", "traits": ["Heartsteel", "Edgelord", "Wildcard"], "cost": 5},
    "Lucian": {"name": "Lucian", "traits": ["Jazz", "Rapidfire"], "cost": 5},
    "Qiyana": {"name": "Qiyana", "traits": ["True Damage", "Crowd Diver"], "cost": 5},
    "Sona": {"name": "Sona", "traits": ["Mixmaster", "Spellweaver"], "cost": 5},
    "Yorick": {"name": "Yorick", "traits": ["Pentakill", "Mosher", "Guardian"], "cost": 5},
    "Ziggs": {"name": "Ziggs", "traits": ["Hyperpop", "Dazzler"], "cost": 5},
}

breakpoints = {
    0: 0,
    6: 1,
    8: 2,
    10: 3,
    12: 4,
}

max_cost = { # given your level, what is a reasonable max cost of a unit you could find
    3: 2,
    4: 2,
    5: 3,
    6: 3,
    7: 3,
    8: 4,
    9: 4,
    10: 5,
}

headliners = {
    1: [100, 0, 0, 0, 0],
    2: [100, 0, 0, 0, 0],
    3: [100, 0, 0, 0, 0],
    4: [80, 20, 0, 0, 0],
    5: [30, 70, 0, 0, 0],
    6: [0, 75, 25, 0, 0],
    7: [0, 40, 60, 0, 0],
    8: [0, 0, 70, 30, 0],
    9: [0, 0, 0, 90, 10],
    10: [0, 0, 0, 30, 70],
    11: [0, 0, 0, 0, 100]
}

shop_odds = {
    1: [100, 0, 0, 0, 0],
    2: [100, 0, 0, 0, 0],
    3: [75, 25, 0, 0, 0],
    4: [55, 30, 15, 0, 0],
    5: [45, 33, 20, 2, 0],
    6: [30, 40, 25, 5, 0],
    7: [19, 35, 35, 10, 1],
    8: [18, 25, 36, 18, 3],
    9: [10, 20, 25, 35, 10],
    10: [5, 10, 20, 40, 25],
    11: [1, 2, 12, 50, 35]
}

bag_size = {
    1: 20,
    2: 18,
    3: 16,
    4: 10,
    5: 9
}

level_reqs = {
    3: 2,
    4: 6,
    5: 10,
    6: 20,
    7: 36,
    8: 48,
    9: 76,
    10: 80
}